# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bematiste/test_git_after_push/ROHSA-GPU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bematiste/test_git_after_push/ROHSA-GPU

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bematiste/test_git_after_push/ROHSA-GPU/CMakeFiles /home/bematiste/test_git_after_push/ROHSA-GPU/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bematiste/test_git_after_push/ROHSA-GPU/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ROHSA-GPU

# Build rule for target.
ROHSA-GPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROHSA-GPU
.PHONY : ROHSA-GPU

# fast build rule for target.
ROHSA-GPU/fast:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/build
.PHONY : ROHSA-GPU/fast

L-BFGS-B-C/src/lbfgsb.o: L-BFGS-B-C/src/lbfgsb.cpp.o

.PHONY : L-BFGS-B-C/src/lbfgsb.o

# target to build an object file
L-BFGS-B-C/src/lbfgsb.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/lbfgsb.cpp.o
.PHONY : L-BFGS-B-C/src/lbfgsb.cpp.o

L-BFGS-B-C/src/lbfgsb.i: L-BFGS-B-C/src/lbfgsb.cpp.i

.PHONY : L-BFGS-B-C/src/lbfgsb.i

# target to preprocess a source file
L-BFGS-B-C/src/lbfgsb.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/lbfgsb.cpp.i
.PHONY : L-BFGS-B-C/src/lbfgsb.cpp.i

L-BFGS-B-C/src/lbfgsb.s: L-BFGS-B-C/src/lbfgsb.cpp.s

.PHONY : L-BFGS-B-C/src/lbfgsb.s

# target to generate assembly for a file
L-BFGS-B-C/src/lbfgsb.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/lbfgsb.cpp.s
.PHONY : L-BFGS-B-C/src/lbfgsb.cpp.s

L-BFGS-B-C/src/linesearch.o: L-BFGS-B-C/src/linesearch.cpp.o

.PHONY : L-BFGS-B-C/src/linesearch.o

# target to build an object file
L-BFGS-B-C/src/linesearch.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/linesearch.cpp.o
.PHONY : L-BFGS-B-C/src/linesearch.cpp.o

L-BFGS-B-C/src/linesearch.i: L-BFGS-B-C/src/linesearch.cpp.i

.PHONY : L-BFGS-B-C/src/linesearch.i

# target to preprocess a source file
L-BFGS-B-C/src/linesearch.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/linesearch.cpp.i
.PHONY : L-BFGS-B-C/src/linesearch.cpp.i

L-BFGS-B-C/src/linesearch.s: L-BFGS-B-C/src/linesearch.cpp.s

.PHONY : L-BFGS-B-C/src/linesearch.s

# target to generate assembly for a file
L-BFGS-B-C/src/linesearch.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/linesearch.cpp.s
.PHONY : L-BFGS-B-C/src/linesearch.cpp.s

L-BFGS-B-C/src/linpack.o: L-BFGS-B-C/src/linpack.cpp.o

.PHONY : L-BFGS-B-C/src/linpack.o

# target to build an object file
L-BFGS-B-C/src/linpack.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/linpack.cpp.o
.PHONY : L-BFGS-B-C/src/linpack.cpp.o

L-BFGS-B-C/src/linpack.i: L-BFGS-B-C/src/linpack.cpp.i

.PHONY : L-BFGS-B-C/src/linpack.i

# target to preprocess a source file
L-BFGS-B-C/src/linpack.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/linpack.cpp.i
.PHONY : L-BFGS-B-C/src/linpack.cpp.i

L-BFGS-B-C/src/linpack.s: L-BFGS-B-C/src/linpack.cpp.s

.PHONY : L-BFGS-B-C/src/linpack.s

# target to generate assembly for a file
L-BFGS-B-C/src/linpack.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/linpack.cpp.s
.PHONY : L-BFGS-B-C/src/linpack.cpp.s

L-BFGS-B-C/src/miniCBLAS.o: L-BFGS-B-C/src/miniCBLAS.cpp.o

.PHONY : L-BFGS-B-C/src/miniCBLAS.o

# target to build an object file
L-BFGS-B-C/src/miniCBLAS.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/miniCBLAS.cpp.o
.PHONY : L-BFGS-B-C/src/miniCBLAS.cpp.o

L-BFGS-B-C/src/miniCBLAS.i: L-BFGS-B-C/src/miniCBLAS.cpp.i

.PHONY : L-BFGS-B-C/src/miniCBLAS.i

# target to preprocess a source file
L-BFGS-B-C/src/miniCBLAS.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/miniCBLAS.cpp.i
.PHONY : L-BFGS-B-C/src/miniCBLAS.cpp.i

L-BFGS-B-C/src/miniCBLAS.s: L-BFGS-B-C/src/miniCBLAS.cpp.s

.PHONY : L-BFGS-B-C/src/miniCBLAS.s

# target to generate assembly for a file
L-BFGS-B-C/src/miniCBLAS.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/miniCBLAS.cpp.s
.PHONY : L-BFGS-B-C/src/miniCBLAS.cpp.s

L-BFGS-B-C/src/print.o: L-BFGS-B-C/src/print.cpp.o

.PHONY : L-BFGS-B-C/src/print.o

# target to build an object file
L-BFGS-B-C/src/print.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/print.cpp.o
.PHONY : L-BFGS-B-C/src/print.cpp.o

L-BFGS-B-C/src/print.i: L-BFGS-B-C/src/print.cpp.i

.PHONY : L-BFGS-B-C/src/print.i

# target to preprocess a source file
L-BFGS-B-C/src/print.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/print.cpp.i
.PHONY : L-BFGS-B-C/src/print.cpp.i

L-BFGS-B-C/src/print.s: L-BFGS-B-C/src/print.cpp.s

.PHONY : L-BFGS-B-C/src/print.s

# target to generate assembly for a file
L-BFGS-B-C/src/print.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/print.cpp.s
.PHONY : L-BFGS-B-C/src/print.cpp.s

L-BFGS-B-C/src/subalgorithms.o: L-BFGS-B-C/src/subalgorithms.cpp.o

.PHONY : L-BFGS-B-C/src/subalgorithms.o

# target to build an object file
L-BFGS-B-C/src/subalgorithms.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/subalgorithms.cpp.o
.PHONY : L-BFGS-B-C/src/subalgorithms.cpp.o

L-BFGS-B-C/src/subalgorithms.i: L-BFGS-B-C/src/subalgorithms.cpp.i

.PHONY : L-BFGS-B-C/src/subalgorithms.i

# target to preprocess a source file
L-BFGS-B-C/src/subalgorithms.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/subalgorithms.cpp.i
.PHONY : L-BFGS-B-C/src/subalgorithms.cpp.i

L-BFGS-B-C/src/subalgorithms.s: L-BFGS-B-C/src/subalgorithms.cpp.s

.PHONY : L-BFGS-B-C/src/subalgorithms.s

# target to generate assembly for a file
L-BFGS-B-C/src/subalgorithms.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/subalgorithms.cpp.s
.PHONY : L-BFGS-B-C/src/subalgorithms.cpp.s

L-BFGS-B-C/src/timer.o: L-BFGS-B-C/src/timer.cpp.o

.PHONY : L-BFGS-B-C/src/timer.o

# target to build an object file
L-BFGS-B-C/src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/timer.cpp.o
.PHONY : L-BFGS-B-C/src/timer.cpp.o

L-BFGS-B-C/src/timer.i: L-BFGS-B-C/src/timer.cpp.i

.PHONY : L-BFGS-B-C/src/timer.i

# target to preprocess a source file
L-BFGS-B-C/src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/timer.cpp.i
.PHONY : L-BFGS-B-C/src/timer.cpp.i

L-BFGS-B-C/src/timer.s: L-BFGS-B-C/src/timer.cpp.s

.PHONY : L-BFGS-B-C/src/timer.s

# target to generate assembly for a file
L-BFGS-B-C/src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/L-BFGS-B-C/src/timer.cpp.s
.PHONY : L-BFGS-B-C/src/timer.cpp.s

algo_rohsa.o: algo_rohsa.cpp.o

.PHONY : algo_rohsa.o

# target to build an object file
algo_rohsa.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/algo_rohsa.cpp.o
.PHONY : algo_rohsa.cpp.o

algo_rohsa.i: algo_rohsa.cpp.i

.PHONY : algo_rohsa.i

# target to preprocess a source file
algo_rohsa.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/algo_rohsa.cpp.i
.PHONY : algo_rohsa.cpp.i

algo_rohsa.s: algo_rohsa.cpp.s

.PHONY : algo_rohsa.s

# target to generate assembly for a file
algo_rohsa.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/algo_rohsa.cpp.s
.PHONY : algo_rohsa.cpp.s

hypercube.o: hypercube.cpp.o

.PHONY : hypercube.o

# target to build an object file
hypercube.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/hypercube.cpp.o
.PHONY : hypercube.cpp.o

hypercube.i: hypercube.cpp.i

.PHONY : hypercube.i

# target to preprocess a source file
hypercube.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/hypercube.cpp.i
.PHONY : hypercube.cpp.i

hypercube.s: hypercube.cpp.s

.PHONY : hypercube.s

# target to generate assembly for a file
hypercube.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/hypercube.cpp.s
.PHONY : hypercube.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/main.cpp.s
.PHONY : main.cpp.s

model.o: model.cpp.o

.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i

.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s

.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) -f CMakeFiles/ROHSA-GPU.dir/build.make CMakeFiles/ROHSA-GPU.dir/model.cpp.s
.PHONY : model.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ROHSA-GPU"
	@echo "... edit_cache"
	@echo "... L-BFGS-B-C/src/lbfgsb.o"
	@echo "... L-BFGS-B-C/src/lbfgsb.i"
	@echo "... L-BFGS-B-C/src/lbfgsb.s"
	@echo "... L-BFGS-B-C/src/linesearch.o"
	@echo "... L-BFGS-B-C/src/linesearch.i"
	@echo "... L-BFGS-B-C/src/linesearch.s"
	@echo "... L-BFGS-B-C/src/linpack.o"
	@echo "... L-BFGS-B-C/src/linpack.i"
	@echo "... L-BFGS-B-C/src/linpack.s"
	@echo "... L-BFGS-B-C/src/miniCBLAS.o"
	@echo "... L-BFGS-B-C/src/miniCBLAS.i"
	@echo "... L-BFGS-B-C/src/miniCBLAS.s"
	@echo "... L-BFGS-B-C/src/print.o"
	@echo "... L-BFGS-B-C/src/print.i"
	@echo "... L-BFGS-B-C/src/print.s"
	@echo "... L-BFGS-B-C/src/subalgorithms.o"
	@echo "... L-BFGS-B-C/src/subalgorithms.i"
	@echo "... L-BFGS-B-C/src/subalgorithms.s"
	@echo "... L-BFGS-B-C/src/timer.o"
	@echo "... L-BFGS-B-C/src/timer.i"
	@echo "... L-BFGS-B-C/src/timer.s"
	@echo "... algo_rohsa.o"
	@echo "... algo_rohsa.i"
	@echo "... algo_rohsa.s"
	@echo "... hypercube.o"
	@echo "... hypercube.i"
	@echo "... hypercube.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

